name: env_univar
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - ld_impl_linux-64=2.40
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.1.0
  - libgomp=13.1.0
  - libnsl=2.0.0
  - libsqlite=3.43.0
  - libuuid=2.38.1
  - libzlib=1.2.13
  - ncurses=6.4
  - openssl=3.1.2
  - pip=23.2.1
  - python=3.10.12
  - readline=8.2
  - setuptools=68.1.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.2.6
  - pip:
      - accelerate==0.24.1
      - agreement==0.1.1
      - aiohttp==3.8.6
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - anyio==4.3.0
      - appdirs==1.4.4
      - asttokens==2.4.1
      - async-timeout==4.0.3
      - attrs==23.1.0
      - audioread==3.0.1
      - beautifulsoup4==4.12.3
      - bioc==2.1
      - bitsandbytes==0.41.2
      - black==22.12.0
      - blessed==1.20.0
      - brotli==1.1.0
      - cachetools==5.3.2
      - certifi==2023.7.22
      - cffi==1.16.0
      - cfgv==3.4.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - coloredlogs==15.0.1
      - comm==0.2.1
      - conllu==4.5.3
      - contourpy==1.2.0
      - cycler==0.12.1
      - datasets==2.14.6
      - debugpy==1.8.0
      - decorator==5.1.1
      - deepspeed==0.12.2
      - dill==0.3.7
      - distlib==0.3.7
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - docopt==0.6.2
      - einops==0.7.0
      - et-xmlfile==1.1.0
      - evaluate==0.4.1
      - exceptiongroup==1.1.3
      - executing==2.0.1
      - ffmpeg==1.4
      - filelock==3.13.1
      - fire==0.5.0
      - flake8==6.1.0
      - fonttools==4.44.0
      - frozenlist==1.4.0
      - fsspec==2023.10.0
      - gdown==5.0.1
      - gitdb==4.0.11
      - gitpython==3.1.40
      - gpustat==1.1.1
      - h11==0.14.0
      - h2==4.1.0
      - hjson==3.1.0
      - hpack==4.0.0
      - httpcore==1.0.4
      - httpx==0.27.0
      - huggingface-hub==0.20.3
      - humanfriendly==10.0
      - hyperframe==6.0.1
      - identify==2.5.32
      - idna==3.4
      - inflate64==1.0.0
      - intervaltree==3.1.0
      - ipykernel==6.28.0
      - ipython==8.17.2
      - ipywidgets==8.1.1
      - isort==5.12.0
      - jedi==0.19.1
      - jinja2==3.1.2
      - joblib==1.3.2
      - jsonlines==4.0.0
      - jupyter-client==8.6.0
      - jupyter-core==5.7.1
      - jupyterlab-widgets==3.0.9
      - kiwisolver==1.4.5
      - kmeans-pytorch==0.3
      - lazy-loader==0.3
      - librosa==0.10.1
      - llama-recipes==0.0.1
      - llvmlite==0.41.1
      - loguru==0.7.2
      - loralib==0.1.2
      - lxml==4.9.3
      - markupsafe==2.1.3
      - matplotlib==3.8.2
      - matplotlib-inline==0.1.6
      - mccabe==0.7.0
      - mpmath==1.3.0
      - msgpack==1.0.7
      - multidict==6.0.4
      - multiprocess==0.70.15
      - multivolumefile==0.2.3
      - mypy-extensions==1.0.0
      - nest-asyncio==1.5.8
      - networkx==3.2.1
      - ninja==1.11.1.1
      - nltk==3.8.1
      - nodeenv==1.8.0
      - numba==0.58.1
      - numpy==1.26.1
      - nusacrowd==0.1.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.535.133
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.52
      - nvidia-nvtx-cu12==12.1.105
      - nvitop==1.3.2
      - openai==1.13.3
      - openpyxl==3.1.2
      - optimum==1.14.0
      - packaging==23.2
      - pandas==2.2.0
      - parso==0.8.3
      - pathspec==0.11.2
      - peft==0.6.0
      - pexpect==4.8.0
      - pillow==10.1.0
      - platformdirs==3.11.0
      - plotly==5.18.0
      - pooch==1.8.0
      - pre-commit==3.5.0
      - prompt-toolkit==3.0.39
      - protobuf==4.25.0
      - psutil==5.9.6
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py-cpuinfo==9.0.0
      - py7zr==0.20.7
      - pyarrow==14.0.0
      - pybcj==1.0.2
      - pycodestyle==2.11.1
      - pycparser==2.21
      - pycryptodomex==3.19.0
      - pydantic==2.4.2
      - pydantic-core==2.10.1
      - pyflakes==3.1.0
      - pygments==2.16.1
      - pynndescent==0.5.11
      - pynvml==11.5.0
      - pyparsing==3.1.1
      - pyppmd==1.1.0
      - pysocks==1.7.1
      - python-dateutil==2.8.2
      - pytorch-ranger==0.1.1
      - pytorch-triton==2.1.0+6e4932cda8
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzmq==25.1.2
      - pyzstd==0.15.9
      - regex==2023.10.3
      - requests==2.31.0
      - responses==0.18.0
      - safetensors==0.4.0
      - scikit-learn==1.4.0
      - scipy==1.11.3
      - seaborn==0.13.0
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.99
      - sentry-sdk==1.34.0
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soundfile==0.12.1
      - soupsieve==2.5
      - soxr==0.3.7
      - stack-data==0.6.3
      - sympy==1.12
      - tenacity==8.2.3
      - tensorboard==2.16.2
      - termcolor==2.3.0
      - texttable==1.7.0
      - threadpoolctl==3.2.0
      - tokenize-rt==5.2.0
      - tokenizers==0.15.1
      - tomli==2.0.1
      - torch==2.2.0.dev20231108+cu121
      - torch-kmeans==0.2.0
      - torch-optimizer==0.3.0
      - torchaudio==2.2.0.dev20231108+cu121
      - torchvision==0.17.0.dev20231108+cu121
      - tornado==6.4
      - tqdm==4.66.1
      - traitlets==5.13.0
      - transformers==4.37.0
      - translate-toolkit==3.11.1
      - triton==2.1.0
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - umap-learn==0.5.5
      - urllib3==2.0.7
      - virtualenv==20.24.7
      - wandb==0.16.0
      - wcwidth==0.2.9
      - widgetsnbextension==4.0.9
      - xxhash==3.4.1
      - yarl==1.9.2
      - zstandard==0.22.0
